version: '3'
services: 
  nginx:
    build:
      dockerfile: nginx.dockerfile
      context: .
    image: pedroe/nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - production-network
    depends_on: 
      - "node1"
      - "node2"
      - "node3"

  mongodb:
    image: bitnami/mongodb
    networks:
      - production-network
  
  node1:
    build: 
      dockerfile: alura-books.dockerfile
      context: .
    image: pedroe/alurabooks
    container_name: aluraNode1
    ports:
      - "3000"
    networks:
      - production-network
    depends_on: 
      - "mongodb"

  node2:
    build: 
      dockerfile: alura-books.dockerfile
      context: .
    image: pedroe/alurabooks
    container_name: aluraNode2
    ports:
      - "3000"
    networks:
      - production-network
    depends_on: 
      - "mongodb"

  node3:
    build: 
      dockerfile: alura-books.dockerfile
      context: .
    image: pedroe/alurabooks
    container_name: aluraNode3
    ports:
      - "3000"
    networks:
      - production-network
    depends_on: 
      - "mongodb"

networks: 
  production-network:
    driver: bridge